spring:
  application:
    name: microservices-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/singh-ank0509/configuration-properties
          clone-on-start: true
          
server:
  port: 7071
        

